apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: ImageStream
    metadata: 
      name: demo-backend
      namespace: demo
      labels:
        app: demo-backend
        project: demo

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: demo-backend
      namespace: demo
      labels:
        app: demo-backend
        project: demo
    spec:
      strategy:
        type: docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      source:
        type: Git
        git: 
          uri: "https://github.com/mk811/quick-platform-demo.git"
          ref: "master"
        contextDir: backend
      output:
        to:
          kind: ImageStreamTag
          name: "demo-backend:latest"
      runPolicy: Serial
      triggers:
        - type: ImageChange
          imageChange: {}

  - apiVersion: v1
    kind: ImageStream
    metadata: 
      name: demo-frontend
      namespace: demo
      labels:
        app: demo-frontend
        project: demo

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: demo-frontend
      namespace: demo
      labels:
        app: demo-frontend
        project: demo
    spec:
      strategy:
        type: docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      source: 
        type: Binary
      output:
        to:
          kind: ImageStreamTag
          name: "demo-frontend:latest"
      runPolicy: Serial
      triggers:
        - type: ImageChange
          imageChange: {}
