apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: demo-backend
      labels:
        app: demo-backend
        project: demo
    spec:
      replicas: 1
      selector:
        app: demo-backend
        project: demo
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: demo-backend
            project: demo
        spec:
          containers:
            - name: backend
              imagePullPolicy: Always
              ports:
                - name: http2-backend
                  containerPort: 3000
              env:
                - name: TZ
                  value: "Asia/Tokyo"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:  
        - imageChangeParams:
            automatic: false
            containerNames:
              - backend
            from:
              kind: ImageStreamTag
              name: 'demo-backend:latest'
          type: ImageChange

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: demo-frontend
      labels:
        app: demo-frontend
        project: demo
    spec:
      replicas: 1
      selector:
        app: demo-frontend
        project: demo
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: demo-frontend
            project: demo
        spec:
          containers:
            - name: frontend
              imagePullPolicy: Always
              ports:
                - name: http2-frontend
                  containerPort: 8080
              env:
                - name: TZ
                  value: "Asia/Tokyo"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - imageChangeParams:
            automatic: false
            containerNames:
              - frontend
            from:
              kind: ImageStreamTag
              name: 'demo-frontend:latest'
          type: ImageChange